import { createDevLogger } from "../../utils/devLogger.js"
import { normalizeQuestionTypeValue } from "./utils/questionType.utils.js"

const devLog = createDevLogger("agent.formatting")
const MAX_QUESTION_TEXT_LENGTH = 1000
const MAX_OPTION_LENGTH = 200
const MAX_OBJECTIVE_ANSWER_LENGTH = 300
const MAX_SUBJECTIVE_ANSWER_LENGTH = 3000

const clampText = (value, maxLength) => {
    return String(value || "")
        .trim()
        .slice(0, maxLength)
}

const buildSafeOptions = (options, safeCorrectAnswer) => {
    const cleaned = (Array.isArray(options) ? options : [])
        .map((option) => clampText(option, MAX_OPTION_LENGTH))
        .filter(Boolean)

    const unique = [...new Set(cleaned)]

    if (safeCorrectAnswer && !unique.includes(safeCorrectAnswer)) {
        unique.push(safeCorrectAnswer)
    }

    // Ensure minimum viable option set for schema validation
    while (unique.length < 2) {
        unique.push(`Option ${unique.length + 1}`)
    }

    return unique
}

const normalizeDifficulty = (difficulty, fallbackDifficulty = "medium") => {
    const value = String(difficulty || fallbackDifficulty || "medium")
        .trim()
        .toLowerCase()

    if (["easy", "medium", "hard"].includes(value)) {
        return value
    }

    return "medium"
}

const ensureMsqHasIncorrectOption = (options, correctOptions) => {
    const safeOptions = [
        ...new Set((Array.isArray(options) ? options : []).filter(Boolean)),
    ]
    let safeCorrectOptions = [
        ...new Set(
            (Array.isArray(correctOptions) ? correctOptions : []).filter(
                Boolean
            )
        ),
    ]

    if (safeOptions.length < 3) {
        const syntheticIncorrect = "None of the above"
        if (!safeOptions.includes(syntheticIncorrect)) {
            safeOptions.push(syntheticIncorrect)
        }
    }

    if (safeCorrectOptions.length >= safeOptions.length) {
        safeCorrectOptions = safeCorrectOptions.slice(
            0,
            Math.max(1, safeOptions.length - 1)
        )
    }

    return {
        options: safeOptions,
        correctOptions: safeCorrectOptions,
    }
}

export const sanitizeQuestionWithFormattingAgent = (
    question,
    {
        requirements = {},
        fallbackQuestionType = "multiple-choice",
        fallbackPoints = 1,
    } = {}
) => {
    const safeQuestionType = normalizeQuestionTypeValue(
        question?.questionType || fallbackQuestionType || "multiple-choice"
    )

    const safeCorrectAnswerObjective = clampText(
        question?.correctAnswer,
        MAX_OBJECTIVE_ANSWER_LENGTH
    )
    const safeCorrectAnswerSubjective = clampText(
        question?.correctAnswer,
        MAX_SUBJECTIVE_ANSWER_LENGTH
    )
    const safeOptions = buildSafeOptions(
        question?.options,
        safeCorrectAnswerObjective
    )

    if (
        safeQuestionType === "short-answer" ||
        safeQuestionType === "long-answer"
    ) {
        return {
            questionText: clampText(
                question?.questionText,
                MAX_QUESTION_TEXT_LENGTH
            ),
            options: [],
            correctAnswer: safeCorrectAnswerSubjective,
            questionType: safeQuestionType,
            points: Number(
                question?.points ||
                    requirements?.marksPerQuestion ||
                    fallbackPoints ||
                    1
            ),
            difficulty: normalizeDifficulty(
                question?.difficulty,
                requirements?.difficultyLevel || "medium"
            ),
            topic: String(question?.topic || "General").trim() || "General",
            explanation: clampText(
                question?.explanation || "Generated by QuizMitra AI",
                500
            ),
        }
    }

    if (safeQuestionType === "true-false") {
        const tfOptions = ["True", "False"]
        const normalizedAnswer =
            String(safeCorrectAnswerObjective || "")
                .trim()
                .toLowerCase() === "true"
                ? "True"
                : "False"

        return {
            questionText: clampText(
                question?.questionText,
                MAX_QUESTION_TEXT_LENGTH
            ),
            options: tfOptions,
            correctAnswer: normalizedAnswer,
            questionType: safeQuestionType,
            points: Number(
                question?.points ||
                    requirements?.marksPerQuestion ||
                    fallbackPoints ||
                    1
            ),
            difficulty: normalizeDifficulty(
                question?.difficulty,
                requirements?.difficultyLevel || "medium"
            ),
            topic: String(question?.topic || "General").trim() || "General",
            explanation: clampText(
                question?.explanation || "Generated by QuizMitra AI",
                500
            ),
        }
    }

    if (safeQuestionType === "multiple-select") {
        const safeCorrectOptions = [
            ...new Set(
                (Array.isArray(question?.correctOptions)
                    ? question.correctOptions
                    : [safeCorrectAnswerObjective]
                )
                    .map((entry) => clampText(entry, MAX_OPTION_LENGTH))
                    .filter(Boolean)
            ),
        ]

        while (safeCorrectOptions.length < 1) {
            safeCorrectOptions.push(safeOptions[0] || "Option 1")
        }

        const mergedOptions = buildSafeOptions(
            [...safeOptions, ...safeCorrectOptions],
            safeCorrectOptions[0]
        )

        const msqSafe = ensureMsqHasIncorrectOption(
            mergedOptions,
            safeCorrectOptions.filter((option) =>
                mergedOptions.includes(option)
            )
        )

        return {
            questionText: clampText(
                question?.questionText,
                MAX_QUESTION_TEXT_LENGTH
            ),
            options: msqSafe.options,
            correctOptions: msqSafe.correctOptions,
            questionType: safeQuestionType,
            points: Number(
                question?.points ||
                    requirements?.marksPerQuestion ||
                    fallbackPoints ||
                    1
            ),
            difficulty: normalizeDifficulty(
                question?.difficulty,
                requirements?.difficultyLevel || "medium"
            ),
            topic: String(question?.topic || "General").trim() || "General",
            explanation: clampText(
                question?.explanation || "Generated by QuizMitra AI",
                500
            ),
        }
    }

    return {
        questionText: clampText(
            question?.questionText,
            MAX_QUESTION_TEXT_LENGTH
        ),
        options: safeOptions,
        correctAnswer: safeCorrectAnswerObjective || safeOptions[0],
        questionType: safeQuestionType,
        points: Number(
            question?.points ||
                requirements?.marksPerQuestion ||
                fallbackPoints ||
                1
        ),
        difficulty: normalizeDifficulty(
            question?.difficulty,
            requirements?.difficultyLevel || "medium"
        ),
        topic: String(question?.topic || "General").trim() || "General",
        explanation: clampText(
            question?.explanation || "Generated by QuizMitra AI",
            500
        ),
    }
}

export const formattingAgent = async (state) => {
    const { verifiedQuestions, requirements, input } = state
    const pipelineRunId = input?.pipelineRunId || "unknown"

    devLog.info("Entered formatting agent", {
        pipelineRunId,
        verifiedCount: verifiedQuestions?.length || 0,
        marksPerQuestion: requirements?.marksPerQuestion,
    })

    const finalQuestions = verifiedQuestions.map((q) =>
        sanitizeQuestionWithFormattingAgent(q, {
            requirements,
            fallbackQuestionType: "multiple-choice",
            fallbackPoints: requirements?.marksPerQuestion || 1,
        })
    )

    return {
        verifiedQuestions: finalQuestions,
        status: "completed",
    }
}
