// apps/api/src/agents/nodes/formatting.node.js

import { createDevLogger } from "../../utils/devLogger.js"

const devLog = createDevLogger("node.formatting")
const MAX_QUESTION_TEXT_LENGTH = 1000
const MAX_OPTION_LENGTH = 200

const clampText = (value, maxLength) => {
    return String(value || "")
        .trim()
        .slice(0, maxLength)
}

const buildSafeOptions = (options, safeCorrectAnswer) => {
    const cleaned = (Array.isArray(options) ? options : [])
        .map((option) => clampText(option, MAX_OPTION_LENGTH))
        .filter(Boolean)

    const unique = [...new Set(cleaned)]

    if (safeCorrectAnswer && !unique.includes(safeCorrectAnswer)) {
        unique.push(safeCorrectAnswer)
    }

    // Ensure minimum viable option set for schema validation
    while (unique.length < 2) {
        unique.push(`Option ${unique.length + 1}`)
    }

    return unique
}

export const formattingNode = async (state) => {
    const { verifiedQuestions, requirements, input } = state
    const pipelineRunId = input?.pipelineRunId || "unknown"

    devLog.info("Entered formatting node", {
        pipelineRunId,
        verifiedCount: verifiedQuestions?.length || 0,
        marksPerQuestion: requirements?.marksPerQuestion,
    })

    // Transform into the schema expected by the database/controller
    const finalQuestions = verifiedQuestions.map((q) => {
        const safeCorrectAnswer = clampText(q.correctAnswer, MAX_OPTION_LENGTH)
        const safeOptions = buildSafeOptions(q.options, safeCorrectAnswer)

        return {
            questionText: clampText(q.questionText, MAX_QUESTION_TEXT_LENGTH),
            options: safeOptions,
            correctAnswer: safeCorrectAnswer || safeOptions[0],
            // correctOptions: [], // explicitly empty or undefined for multiple-choice
            questionType: "multiple-choice", // Defaulting for MVP
            points: requirements.marksPerQuestion || 1,
            difficulty: (
                q.difficulty ||
                requirements.difficultyLevel ||
                "medium"
            ).toLowerCase(),
            topic: q.topic || "General",
            explanation: "Generated by QuizMitra AI",
        }
    })

    return {
        verifiedQuestions: finalQuestions,
        status: "completed",
    }
}
