// apps/api/src/agents/nodes/formatting.node.js

import { createDevLogger } from "../../utils/devLogger.js"

const devLog = createDevLogger("node.formatting")

export const formattingNode = async (state) => {
    const { verifiedQuestions, requirements, input } = state
    const pipelineRunId = input?.pipelineRunId || "unknown"

    devLog.info("Entered formatting node", {
        pipelineRunId,
        verifiedCount: verifiedQuestions?.length || 0,
        marksPerQuestion: requirements?.marksPerQuestion,
    })

    // Transform into the schema expected by the database/controller
    const finalQuestions = verifiedQuestions.map((q) => ({
        questionText: q.questionText,
        options: q.options,
        correctAnswer: q.correctAnswer,
        // correctOptions: [], // explicitly empty or undefined for multiple-choice
        questionType: "multiple-choice", // Defaulting for MVP
        points: requirements.marksPerQuestion || 1,
        difficulty: q.difficulty || requirements.difficultyLevel || "medium",
        topic: q.topic || "General",
        explanation: "Generated by QuizMitra AI",
    }))

    return {
        verifiedQuestions: finalQuestions,
        status: "completed",
    }
}
