// apps/api/src/agents/nodes/formatting.node.js

import { createDevLogger } from "../../utils/devLogger.js"

const devLog = createDevLogger("node.formatting")
const MAX_QUESTION_TEXT_LENGTH = 1000
const MAX_OPTION_LENGTH = 200

const clampText = (value, maxLength) => {
    return String(value || "")
        .trim()
        .slice(0, maxLength)
}

const buildSafeOptions = (options, safeCorrectAnswer) => {
    const cleaned = (Array.isArray(options) ? options : [])
        .map((option) => clampText(option, MAX_OPTION_LENGTH))
        .filter(Boolean)

    const unique = [...new Set(cleaned)]

    if (safeCorrectAnswer && !unique.includes(safeCorrectAnswer)) {
        unique.push(safeCorrectAnswer)
    }

    // Ensure minimum viable option set for schema validation
    while (unique.length < 2) {
        unique.push(`Option ${unique.length + 1}`)
    }

    return unique
}

const normalizeDifficulty = (difficulty, fallbackDifficulty = "medium") => {
    const value = String(difficulty || fallbackDifficulty || "medium")
        .trim()
        .toLowerCase()

    if (["easy", "medium", "hard"].includes(value)) {
        return value
    }

    return "medium"
}

export const sanitizeQuestionWithFormattingAgent = (
    question,
    {
        requirements = {},
        fallbackQuestionType = "multiple-choice",
        fallbackPoints = 1,
    } = {}
) => {
    const safeCorrectAnswer = clampText(
        question?.correctAnswer,
        MAX_OPTION_LENGTH
    )
    const safeOptions = buildSafeOptions(question?.options, safeCorrectAnswer)
    const safeQuestionType = String(
        question?.questionType || fallbackQuestionType || "multiple-choice"
    ).trim()

    return {
        questionText: clampText(
            question?.questionText,
            MAX_QUESTION_TEXT_LENGTH
        ),
        options: safeOptions,
        correctAnswer: safeCorrectAnswer || safeOptions[0],
        questionType: safeQuestionType,
        points: Number(
            question?.points ||
                requirements?.marksPerQuestion ||
                fallbackPoints ||
                1
        ),
        difficulty: normalizeDifficulty(
            question?.difficulty,
            requirements?.difficultyLevel || "medium"
        ),
        topic: String(question?.topic || "General").trim() || "General",
        explanation: clampText(
            question?.explanation || "Generated by QuizMitra AI",
            500
        ),
    }
}

export const formattingNode = async (state) => {
    const { verifiedQuestions, requirements, input } = state
    const pipelineRunId = input?.pipelineRunId || "unknown"

    devLog.info("Entered formatting node", {
        pipelineRunId,
        verifiedCount: verifiedQuestions?.length || 0,
        marksPerQuestion: requirements?.marksPerQuestion,
    })

    // Transform into the schema expected by the database/controller
    const finalQuestions = verifiedQuestions.map((q) =>
        sanitizeQuestionWithFormattingAgent(q, {
            requirements,
            fallbackQuestionType: "multiple-choice",
            fallbackPoints: requirements?.marksPerQuestion || 1,
        })
    )

    return {
        verifiedQuestions: finalQuestions,
        status: "completed",
    }
}
